### ISSUE TITLE
Stickers Correction

### ISSUE THREAD

**Issue by hyoretsu** [Hyoretsu/EXO-WAStickerApps#1]
Make sure to flip them to the right side someday.

**Comment by hyoretsu** [comment]
They turned out to be really weird if flipped to the right.

**Comment by arhciey** [comment]
Hello..how to download the sticker? Ty so much

**Comment by arhciey** [comment]
I cant found it on playstore

**Comment by hyoretsu** [comment]
Just go to releases page and download the APK
